#! /bin/sh

DEFAULT_EXEC="echo"

MM="$(file --mime-type "$1" | sed -e 's/^.*:\ //g')"
E=$DEFAULT_EXEC

case $MM in
	"application/x-executable" )
		E="exec"	;;
	"text/plain" )
		E="geany"	;;
esac

$E "$1" &>/dev/null

exit 0
